name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, Test, Docker Push, and Heroku deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      # Install modules
      - name: Install modules
        run: npm install

      # Run tests
      - name: Run Jest tests
        run: npm run test

      # Webpack build page
      - name: Webpack build
        run: npm run build
      
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_TOKEN }}
          DOCKERFILE: Dockerfile
          IMAGE_NAME: yupiel/newspaper-app
          TAG_NAME: latest
          LATEST: true

      - name: Docker Build & Push to GitHub Package
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: yupiel
          PASSWORD: ${{ secrets.GIT_TOKEN }}
          REGISTRY: docker.pkg.github.com
          DOCKERFILE: Dockerfile
          IMAGE_NAME: newspaper-app
          TAG_NAME: latest
          LATEST: true
      
      # Deploy to Heroku Repository
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.6.8
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          # Email that you use with heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          # The appname to use for deploying/updating
          heroku_app_name: iea-newspaper-app
          # The branch that you would like to deploy to Heroku
          branch: main
          # Will deploy using Dockerfile in project root.
          usedocker: true
          # Type of heroku process (web, worker, etc). This option only makes sense when usedocker enabled
          docker_heroku_process_type: web
